import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'language';

export const translations = {
  vi: {
    languageName: 'Tiếng Việt',
    toggleLanguage: 'Chuyển sang tiếng Anh',
    nav: {
      dashboard: 'Tổng quan',
      contracts: 'Hợp đồng',
      invoices: 'Hóa đơn',
      quotations: 'Báo giá',
      receipts: 'Phiếu thu/chi',
      chat: 'Tin nhắn',
      customers: 'Khách hàng',
      search: 'Tìm kiếm',
      trash: 'Thùng rác',
      admin: 'Admin',
      logout: 'Đăng xuất',
    },
    chat: {
      title: 'Tin nhắn',
      searchUser: 'Tìm người dùng...',
      noUsers: 'Không có người dùng',
      selectConversation: 'Chọn một người để bắt đầu trò chuyện',
      noMessages: 'Chưa có tin nhắn. Hãy gửi lời chào!',
      messagePlaceholder: 'Nhập tin nhắn...',
      online: 'Đang hoạt động',
      typing: 'Đang nhập...',
      yesterday: 'Hôm qua',
      deleteMessage: 'Xóa tin nhắn',
      confirmDelete: 'Xóa tin nhắn này?',
    },
    common: {
      allStatuses: 'Tất cả trạng thái',
      back: 'Quay lại',
      cancel: 'Hủy',
      create: 'Tạo',
      save: 'Lưu',
      status: 'Trạng thái',
      customer: 'Khách hàng',
      title: 'Tiêu đề',
      value: 'Giá trị',
      refresh: 'Làm mới',
      viewAll: 'Xem tất cả',
      list: 'Danh sách',
      days: 'ngày',
      files: 'File',
      documents: 'Tài liệu',
      contracts: 'Hợp đồng',
      transactions: 'giao dịch',
      activities: 'hoạt động',
      searchDocuments: 'Tìm tài liệu...',
    },
    table: {
      documentNumber: 'Số tài liệu',
      title: 'Tiêu đề',
      customer: 'Khách hàng',
      amount: 'Số tiền',
      dueDate: 'Hạn thanh toán',
      paid: 'Thanh toán',
      status: 'Trạng thái',
      validUntil: 'Hiệu lực đến',
      paymentMethod: 'Phương thức',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Tổng quan quản lý tài liệu & hợp đồng',
      totalContracts: 'Tổng hợp đồng',
      activeContracts: 'Đang hoạt động',
      expiredContracts: 'Đã hết hạn',
      totalContractValue: 'Tổng giá trị HĐ',
      totalInvoices: 'Tổng hóa đơn',
      unpaidInvoices: 'Hóa đơn chưa TT',
      overdueInvoices: 'Hóa đơn quá hạn',
      totalPaid: 'Đã thu',
      outstanding: 'Còn phải thu',
      latestPayment: 'Lần thu gần nhất',
      contractsUnit: 'Hợp đồng',
      invoicesUnit: 'Hóa đơn',
      upcomingTitle: 'Sắp hết hạn',
      upcomingSubtitle: 'Hợp đồng hết hạn trong 30 ngày tới',
      noUpcomingTitle: 'Không có hợp đồng sắp hết hạn',
      noUpcomingSubtitle: 'Các hợp đồng sắp hết hạn trong 30 ngày tới sẽ hiển thị tại đây',
      contractNumber: 'Số HĐ',
      endDate: 'Hết hạn',
      remaining: 'Còn lại',
      cardContracts: 'Hợp đồng',
      cardContractsCaption: 'Tổng số hợp đồng',
      cardInvoices: 'Hóa đơn',
      cardInvoicesCaption: 'Tổng số hóa đơn',
      cardQuotations: 'Báo giá',
      cardQuotationsCaption: 'Tổng số báo giá',
      cardVouchers: 'Phiếu thu/chi',
      cardVouchersCaption: 'Tổng số phiếu',
      cardUnpaid: 'Chưa thanh toán',
      cardUnpaidCaption: 'Hóa đơn chưa thanh toán',
      cardOverdue: 'Quá hạn',
      cardOverdueCaption: 'Hóa đơn quá hạn',
      inProgress: 'Đang thực hiện',
      completed: 'Đã hoàn thành',
      paid: 'Đã thanh toán',
      unpaid: 'Chưa thanh toán',
      accepted: 'Đã chấp nhận',
      notAccepted: 'Chưa chấp nhận',
      receipts: 'Phiếu thu',
      vouchers: 'Phiếu chi',
      viewDetail: 'Xem chi tiết',
      revenueTitle: 'Doanh thu (VND)',
      invoiceStatusTitle: 'Tình trạng hóa đơn',
      overdue: 'Quá hạn',
      totalLabel: 'Tổng số',
      recentContracts: 'Hợp đồng gần đây',
      recentInvoices: 'Hóa đơn gần đây',
      recentQuotations: 'Báo giá gần đây',
      recentVouchers: 'Phiếu thu/chi gần đây',
      viewAll: 'Xem tất cả',
      code: 'Mã',
      amount: 'Số tiền',
      type: 'Loại',
      noData: 'Chưa có dữ liệu',
    },
    customerDetail: {
      notFound: 'Không tìm thấy khách hàng',
      back: 'Quay lại khách hàng',
      profile: 'Hồ sơ khách hàng',
      missingTaxCode: 'Chưa có MST',
      contractCount: 'Số hợp đồng',
      contractsTitle: 'Danh sách hợp đồng',
      noContracts: 'Chưa có hợp đồng',
      recentPayments: 'Thanh toán gần đây',
      noPayments: 'Chưa có thanh toán',
      activityTitle: 'Lịch sử giao dịch',
      noActivity: 'Chưa có lịch sử',
      unknownMethod: 'Không rõ phương thức',
    },
    contractDetail: {
      notFound: 'Không tìm thấy hợp đồng',
      back: 'Quay lại danh sách',
      startDate: 'Ngày bắt đầu',
      endDate: 'Ngày kết thúc',
      customerEmail: 'Email KH',
      contractFiles: 'Tệp hợp đồng',
      totalPaid: 'Đã thu',
      outstanding: 'Còn phải thu',
      relatedDocuments: 'Tài liệu liên quan',
      contractFilesCount: 'File hợp đồng',
      paymentTracking: 'Theo dõi thanh toán',
      paymentCount: 'lần thu',
      recordPayment: 'Ghi nhận thu',
      noPayments: 'Chưa ghi nhận thanh toán',
      documentCenter: 'Trung tâm tài liệu',
      documentCenterSubtitle: 'Tất cả tài liệu liên quan đến hợp đồng',
      appendix: 'Phụ lục',
      noEffectiveDate: 'Chưa có ngày hiệu lực',
      noRelatedDocuments: 'Chưa có tài liệu liên quan',
      appendicesTitle: 'Phụ lục hợp đồng',
      addAppendix: 'Thêm phụ lục',
      noAppendices: 'Chưa có phụ lục',
      timeline: 'Timeline',
      noTimeline: 'Chưa có timeline',
      paymentModalTitle: 'Ghi nhận thanh toán',
      amount: 'Số tiền',
      paidAt: 'Ngày thu',
      method: 'Phương thức',
      methodPlaceholder: 'Chuyển khoản, tiền mặt...',
      reference: 'Mã tham chiếu',
      note: 'Ghi chú',
      description: 'Mô tả',
      effectiveDate: 'Ngày hiệu lực',
      attachments: 'Tệp đính kèm',
      totalInvoicesAmount: 'Tổng tiền các hóa đơn',
      ocrInvoiceName: 'Tên hóa đơn',
      versionName: 'Tên phiên bản',
      ocrTotalQuantity: 'Tổng số lượng',
      ocrTotalPrice: 'Tổng giá',
      savePayment: 'Lưu thanh toán',
    },
    documentDetail: {
      notFound: 'Không tìm thấy tài liệu',
      back: 'Quay lại',
      customer: 'Khách hàng',
      tabInfo: 'Thông tin',
      tabVersions: 'Phiên bản',
      tabActivity: 'Nhật ký',
      tabComments: 'Bình luận',
      view: 'Xem',
      viewVersion: 'Xem phiên bản',
      uploading: 'Đang tải lên...',
      addVersion: 'Thêm phiên bản mới',
      selectVersion: '-- Chọn phiên bản --',
      noVersions: 'Chưa có phiên bản. Upload file để tạo phiên bản đầu tiên.',
      version: 'Phiên bản',
      saveName: 'Lưu tên',
      cancel: 'Hủy',
      renameVersion: 'Đổi tên phiên bản',
      deleteVersion: 'Xóa phiên bản',
      confirmDeleteVersion: 'Xóa phiên bản này?',
      unknown: 'Không rõ',
      noActivity: 'Chưa có hoạt động',
      commentPlaceholder: 'Viết bình luận...',
      status: 'Trạng thái',
      close: 'Đóng',
      scanLocal: 'Quét local OCR',
      scanAdvanced: 'Quét OCR nâng cao',
      noOcrText: 'Chưa có nội dung OCR. Upload file PDF/ảnh và bấm Quét lại.',
      addItem: 'Thêm món',
      saving: 'Đang lưu...',
      saveOcr: 'Lưu thông tin OCR',
      invoiceName: 'Tên hóa đơn',
      seller: 'Đơn vị bán',
      totalOcr: 'Tổng tiền OCR',
      itemsTitle: 'Thông tin món hàng từ OCR',
      itemName: 'Tên món',
      qty: 'SL',
      unitPrice: 'Đơn giá',
      amount: 'Thành tiền',
      noItems: 'OCR chưa nhận diện được món hàng',
      ocrFailed: 'OCR thất bại',
      saveOcrFailed: 'Lưu thông tin OCR thất bại',
    },
    documentTypes: {
      contract: 'Hợp đồng',
      invoice: 'Hóa đơn',
      quotation: 'Báo giá',
      appendix: 'Phụ lục',
      acceptance_report: 'Biên bản nghiệm thu',
      receipt: 'Phiếu thu',
      payment_voucher: 'Phiếu chi',
    },
    documentForm: {
      sectionGeneral: 'Thông tin chung',
      sectionValue: 'Giá trị',
      sectionTime: 'Thời gian',
      sectionPayment: 'Thanh toán',
      sectionContent: 'Nội dung',
      sectionNote: 'Ghi chú',
      sectionFiles: 'Tệp đính kèm',
      documentNumber: 'Số chứng từ',
      title: 'Tiêu đề',
      customer: 'Khách hàng',
      selectCustomer: 'Chọn khách hàng',
      contractType: 'Loại hợp đồng',
      manager: 'Người phụ trách',
      department: 'Phòng ban',
      invoiceForm: 'Mẫu số',
      invoiceSerial: 'Ký hiệu',
      invoiceType: 'Loại hóa đơn',
      voucherType: 'Loại phiếu',
      valueBeforeTax: 'Giá trị trước thuế',
      vat: 'Thuế VAT',
      value: 'Tổng giá trị',
      currency: 'Tiền tệ',
      exchangeRate: 'Tỷ giá',
      amount: 'Thành tiền',
      discount: 'Chiết khấu',
      total: 'Tổng tiền',
      paidAmount: 'Số tiền đã trả',
      signDate: 'Ngày ký',
      startDate: 'Ngày hiệu lực',
      endDate: 'Ngày hết hạn',
      termMonths: 'Thời hạn (tháng)',
      createdDate: 'Ngày lập',
      issueDate: 'Ngày phát hành',
      dueDate: 'Hạn thanh toán',
      validUntil: 'Hết hiệu lực',
      paymentTerms: 'Điều khoản thanh toán',
      paymentMethod: 'Hình thức thanh toán',
      paymentInstallments: 'Số lần thanh toán',
      paid: 'Đã thanh toán',
      supplier: 'Nhà cung cấp',
      preparedBy: 'Người lập',
      approvedBy: 'Người duyệt',
      partyType: 'Đối tượng',
      partyCustomer: 'Khách hàng',
      partySupplier: 'Nhà cung cấp',
      partyEmployee: 'Nhân viên',
      reason: 'Lý do',
      note: 'Diễn giải',
      status: 'Trạng thái',
      description: 'Mô tả',
      specialTerms: 'Điều khoản đặc biệt',
      internalNote: 'Ghi chú nội bộ',
      files: 'Tệp đính kèm (PDF, ảnh, DOCX, XLSX)',
      cancel: 'Hủy',
      create: 'Tạo mới',
      saving: 'Đang lưu...',
      saveFailed: 'Lưu thất bại',
      paymentMethodPlaceholder: 'Tiền mặt, chuyển khoản, QR, thẻ...',
    },
    statuses: {
      draft: 'Bản nháp',
      pending: 'Đang chờ',
      pending_sign: 'Chờ ký',
      signed: 'Đã ký',
      in_progress: 'Đang thực hiện',
      completed: 'Hoàn thành',
      active: 'Đang hoạt động',
      expired: 'Hết hạn',
      terminated: 'Đã chấm dứt',
      sent: 'Đã gửi',
      viewed: 'Đã xem',
      partial: 'Thanh toán một phần',
      paid: 'Đã thanh toán',
      overdue: 'Quá hạn',
      cancelled: 'Đã hủy',
      accepted: 'Đã chấp nhận',
      rejected: 'Từ chối',
      confirmed: 'Đã xác nhận',
      pending_approval: 'Chờ duyệt',
      archived: 'Đã lưu trữ',
      approved: 'Đã duyệt',
    },
  },
  en: {
    languageName: 'English',
    toggleLanguage: 'Switch to Vietnamese',
    nav: {
      dashboard: 'Overview',
      contracts: 'Contracts',
      invoices: 'Invoices',
      quotations: 'Quotations',
      receipts: 'Receipts',
      chat: 'Messages',
      customers: 'Customers',
      search: 'Search',
      trash: 'Trash',
      admin: 'Admin',
      logout: 'Log out',
    },
    chat: {
      title: 'Messages',
      searchUser: 'Search users...',
      noUsers: 'No users',
      selectConversation: 'Select someone to start chatting',
      noMessages: 'No messages yet. Say hi!',
      messagePlaceholder: 'Type a message...',
      online: 'Online',
      typing: 'Typing...',
      yesterday: 'Yesterday',
      deleteMessage: 'Delete message',
      confirmDelete: 'Delete this message?',
    },
    common: {
      allStatuses: 'All statuses',
      back: 'Back',
      cancel: 'Cancel',
      create: 'Create',
      save: 'Save',
      status: 'Status',
      customer: 'Customer',
      title: 'Title',
      value: 'Value',
      refresh: 'Refresh',
      viewAll: 'View all',
      list: 'List',
      days: 'days',
      files: 'Files',
      documents: 'Documents',
      contracts: 'Contracts',
      transactions: 'transactions',
      activities: 'activities',
      searchDocuments: 'Search documents...',
    },
    table: {
      documentNumber: 'Document No.',
      title: 'Title',
      customer: 'Customer',
      amount: 'Amount',
      dueDate: 'Due date',
      paid: 'Payment',
      status: 'Status',
      validUntil: 'Valid until',
      paymentMethod: 'Payment method',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Document and contract management overview',
      totalContracts: 'Total contracts',
      activeContracts: 'Active',
      expiredContracts: 'Expired',
      totalContractValue: 'Total contract value',
      totalInvoices: 'Total invoices',
      unpaidInvoices: 'Unpaid invoices',
      overdueInvoices: 'Overdue invoices',
      totalPaid: 'Received',
      outstanding: 'Outstanding',
      latestPayment: 'Latest payment',
      contractsUnit: 'Contracts',
      invoicesUnit: 'Invoices',
      upcomingTitle: 'Expiring soon',
      upcomingSubtitle: 'Contracts expiring in the next 30 days',
      noUpcomingTitle: 'No contracts expiring soon',
      noUpcomingSubtitle: 'Contracts expiring in the next 30 days will appear here',
      contractNumber: 'Contract No.',
      endDate: 'End date',
      remaining: 'Remaining',
      cardContracts: 'Contracts',
      cardContractsCaption: 'Total contracts',
      cardInvoices: 'Invoices',
      cardInvoicesCaption: 'Total invoices',
      cardQuotations: 'Quotations',
      cardQuotationsCaption: 'Total quotations',
      cardVouchers: 'Receipts/Vouchers',
      cardVouchersCaption: 'Total vouchers',
      cardUnpaid: 'Unpaid',
      cardUnpaidCaption: 'Unpaid invoices',
      cardOverdue: 'Overdue',
      cardOverdueCaption: 'Overdue invoices',
      inProgress: 'In progress',
      completed: 'Completed',
      paid: 'Paid',
      unpaid: 'Unpaid',
      accepted: 'Accepted',
      notAccepted: 'Not accepted',
      receipts: 'Receipts',
      vouchers: 'Payment vouchers',
      viewDetail: 'View detail',
      revenueTitle: 'Revenue (VND)',
      invoiceStatusTitle: 'Invoice status',
      overdue: 'Overdue',
      totalLabel: 'Total',
      recentContracts: 'Recent contracts',
      recentInvoices: 'Recent invoices',
      recentQuotations: 'Recent quotations',
      recentVouchers: 'Recent receipts/vouchers',
      viewAll: 'View all',
      code: 'Code',
      amount: 'Amount',
      type: 'Type',
      noData: 'No data',
    },
    customerDetail: {
      notFound: 'Customer not found',
      back: 'Back to customers',
      profile: 'Customer Profile',
      missingTaxCode: 'No tax code',
      contractCount: 'Contract count',
      contractsTitle: 'Contract list',
      noContracts: 'No contracts yet',
      recentPayments: 'Recent payments',
      noPayments: 'No payments yet',
      activityTitle: 'Transaction history',
      noActivity: 'No history yet',
      unknownMethod: 'Unknown method',
    },
    contractDetail: {
      notFound: 'Contract not found',
      back: 'Back to list',
      startDate: 'Start date',
      endDate: 'End date',
      customerEmail: 'Customer email',
      contractFiles: 'Contract files',
      totalPaid: 'Received',
      outstanding: 'Outstanding',
      relatedDocuments: 'Related documents',
      contractFilesCount: 'Contract files',
      paymentTracking: 'Payment tracking',
      paymentCount: 'payments',
      recordPayment: 'Record payment',
      noPayments: 'No payments recorded',
      documentCenter: 'Document Center',
      documentCenterSubtitle: 'All documents related to this contract',
      appendix: 'Appendix',
      noEffectiveDate: 'No effective date',
      noRelatedDocuments: 'No related documents yet',
      appendicesTitle: 'Contract appendices',
      addAppendix: 'Add appendix',
      noAppendices: 'No appendices yet',
      timeline: 'Timeline',
      noTimeline: 'No timeline yet',
      paymentModalTitle: 'Record payment',
      amount: 'Amount',
      paidAt: 'Payment date',
      method: 'Method',
      methodPlaceholder: 'Bank transfer, cash...',
      reference: 'Reference',
      note: 'Note',
      description: 'Description',
      effectiveDate: 'Effective date',
      attachments: 'Attachments',
      totalInvoicesAmount: 'Total invoice amount',
      ocrInvoiceName: 'Invoice name',
      versionName: 'Version name',
      ocrTotalQuantity: 'Total quantity',
      ocrTotalPrice: 'Total price',
      savePayment: 'Save payment',
    },
    documentDetail: {
      notFound: 'Document not found',
      back: 'Back',
      customer: 'Customer',
      tabInfo: 'Info',
      tabVersions: 'Versions',
      tabActivity: 'Activity',
      tabComments: 'Comments',
      view: 'View',
      viewVersion: 'View version',
      uploading: 'Uploading...',
      addVersion: 'Add new version',
      selectVersion: '-- Select version --',
      noVersions: 'No versions yet. Upload a file to create the first version.',
      version: 'Version',
      saveName: 'Save name',
      cancel: 'Cancel',
      renameVersion: 'Rename version',
      deleteVersion: 'Delete version',
      confirmDeleteVersion: 'Delete this version?',
      unknown: 'Unknown',
      noActivity: 'No activity yet',
      commentPlaceholder: 'Write a comment...',
      status: 'Status',
      close: 'Close',
      scanLocal: 'Local OCR scan',
      scanAdvanced: 'Advanced OCR scan',
      noOcrText: 'No OCR content yet. Upload a PDF/image and click Scan.',
      addItem: 'Add item',
      saving: 'Saving...',
      saveOcr: 'Save OCR data',
      invoiceName: 'Invoice name',
      seller: 'Seller',
      totalOcr: 'OCR total',
      itemsTitle: 'OCR line items',
      itemName: 'Item',
      qty: 'Qty',
      unitPrice: 'Unit price',
      amount: 'Amount',
      noItems: 'OCR did not detect any items',
      ocrFailed: 'OCR failed',
      saveOcrFailed: 'Failed to save OCR data',
    },
    documentTypes: {
      contract: 'Contract',
      invoice: 'Invoice',
      quotation: 'Quotation',
      appendix: 'Appendix',
      acceptance_report: 'Acceptance report',
      receipt: 'Receipt',
      payment_voucher: 'Payment voucher',
    },
    documentForm: {
      sectionGeneral: 'General information',
      sectionValue: 'Value',
      sectionTime: 'Dates',
      sectionPayment: 'Payment',
      sectionContent: 'Content',
      sectionNote: 'Notes',
      sectionFiles: 'Attachments',
      documentNumber: 'Document number',
      title: 'Title',
      customer: 'Customer',
      selectCustomer: 'Select customer',
      contractType: 'Contract type',
      manager: 'Person in charge',
      department: 'Department',
      invoiceForm: 'Form number',
      invoiceSerial: 'Serial',
      invoiceType: 'Invoice type',
      voucherType: 'Voucher type',
      valueBeforeTax: 'Value before tax',
      vat: 'VAT',
      value: 'Total value',
      currency: 'Currency',
      exchangeRate: 'Exchange rate',
      amount: 'Subtotal',
      discount: 'Discount',
      total: 'Total',
      paidAmount: 'Paid amount',
      signDate: 'Sign date',
      startDate: 'Effective date',
      endDate: 'Expiry date',
      termMonths: 'Term (months)',
      createdDate: 'Created date',
      issueDate: 'Issue date',
      dueDate: 'Due date',
      validUntil: 'Valid until',
      paymentTerms: 'Payment terms',
      paymentMethod: 'Payment method',
      paymentInstallments: 'Number of installments',
      paid: 'Paid',
      supplier: 'Supplier',
      preparedBy: 'Prepared by',
      approvedBy: 'Approved by',
      partyType: 'Counterparty',
      partyCustomer: 'Customer',
      partySupplier: 'Supplier',
      partyEmployee: 'Employee',
      reason: 'Reason',
      note: 'Description',
      status: 'Status',
      description: 'Description',
      specialTerms: 'Special terms',
      internalNote: 'Internal note',
      files: 'Attachments (PDF, image, DOCX, XLSX)',
      cancel: 'Cancel',
      create: 'Create',
      saving: 'Saving...',
      saveFailed: 'Failed to save',
      paymentMethodPlaceholder: 'Cash, bank transfer, QR, card...',
    },
    statuses: {
      draft: 'Draft',
      pending: 'Pending',
      pending_sign: 'Pending sign',
      signed: 'Signed',
      in_progress: 'In progress',
      completed: 'Completed',
      active: 'Active',
      expired: 'Expired',
      terminated: 'Terminated',
      sent: 'Sent',
      viewed: 'Viewed',
      partial: 'Partial',
      paid: 'Paid',
      overdue: 'Overdue',
      cancelled: 'Cancelled',
      accepted: 'Accepted',
      rejected: 'Rejected',
      confirmed: 'Confirmed',
      pending_approval: 'Pending approval',
      archived: 'Archived',
      approved: 'Approved',
    },
  },
};

function readLanguage() {
  return localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'vi';
}

function getByPath(source, path) {
  return path.split('.').reduce((obj, key) => obj?.[key], source);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(readLanguage);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const dictionary = translations[language];
    return {
      language,
      locale: language === 'vi' ? 'vi-VN' : 'en-US',
      setLanguage,
      toggleLanguage: () => setLanguage((prev) => (prev === 'vi' ? 'en' : 'vi')),
      t: (path) => getByPath(dictionary, path) || path,
      statusLabel: (status) => dictionary.statuses[status] || status,
      documentTypeLabel: (type) => dictionary.documentTypes[type] || type,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
